### PR TITLE
Add MultiCastActionVarFrame to LayoutManager

### PR DESCRIPTION
**Pull request by FunkeytownGH**
Updates addon for wrath classic 

Gives control of the totem bar to the layout manager.

### CODE REVIEW

**Comment by FunkeytownGH** [comment]
Hey @domino54 . I saw that this addon was sort of left dormant after wrath launch. Not sure this is all that's needed to update it for wrath, but it's what I needed to make it usable for my shaman.  Hope this helps others who end up finding this PR

**Comment by 20CerrigMan22** [comment]
Hey @FunkeytownGH Thanks for the link and help. But I'm afraid I am useless with this type of thing. how do i input this to fix it? spent a few hours over a couple days looking in different places. re-downloading copy pasting, not knowing what i'm doing. Again thanks for the help, but this is beyond me :D if you could let me know how to input this it would be much appreciated.

Thank you :)

**Comment by FunkeytownGH** [comment]
Yeah I can help @20CerrigMan22, do you just wanna add me on discord?  Funkeytown#8849

**Comment by zdinch** [comment]
Hi! Does it work in Woltk classic?

**Comment by FunkeytownGH** [comment]
> Hi! Does it work in Woltk classic?

Yep that's the whole point of this PR.  To fix it for wrath classic

**Comment by zdinch** [comment]
> > Hi! Does it work in Woltk classic?
> 
> Yep that's the whole point of this PR. To fix it for wrath classic

Oh thanks! I used to use it a lot in Classic but it stopped working, how can we know when it works?

Thank you!

**Pull request closed without merging**
